### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by Ahbrosha** [sameersbn/docker-openfire#7]
Openfire version 3.10 is released. Please update your Dockerfile.

**Comment by sameersbn** [comment]
@Ahbrosha i am aware. Since this is the first major version update I need to make sure that the `3.9.x` users can upgrade to `3.10.x` without any issues.

**Comment by SolidNerd** [comment]
:+1:

**Comment by rtrauntvein** [comment]
The current `3.10` release is quite unstable.  I had it running on a non-docker system and it was constantly eating up 100% CPU.

**Comment by sameersbn** [comment]
@rtrauntvein you mean the upstream version?

**Comment by sameersbn** [comment]
@rtrauntvein are you sure about this. I don't see CPU load issues with openfire `3.10` running inside docker. If you want to test it out, in the dockerfile, can change the line `ENV OPENFIRE_VERSION 3.9.3` to `ENV OPENFIRE_VERSION 3.10.0` and build the image.

Note: do not use this over your existing openfire or database container data. It will not migrate your data from the old version to new. Isolate your tests from the `3.9.3` container. Perhaps test it out on a different host.

**Comment by sameersbn** [comment]
I have upgrade to openfire `3.10.0` in the `sameersbn/openfire:latest`. I had to make a couple of changes in the image file and directory structure and so I want to make sure that the image works without any issues for existing users.

If you guys could test out the `latest` image and let me know the results it would be great... Following which I will make tagged releases of the image.

P.S. Please do not test it out on your production servers and/or take a backup of the database and openfire data volume before testing.

Thank you..

**Comment by sameersbn** [comment]
scratch that..  its broken. avoid the latest build for the moment or any build above `3.9.3-4` for that matter

**Comment by sameersbn** [comment]
image with openfire `3.10.2` is now available.

**Comment by white-gecko** [comment]
Sorry for commenting on this closed issue. Openfire 4.0.0 is available, the server frequently tells me to update.

**Comment by sameersbn** [comment]
have noticed that openfire 4 is out. need to figure out the upgrade path from 3.10.x to make sure existing users can upgrade without issues.
