### ISSUE TITLE
Failing to add the admin account

### ISSUE THREAD

**Issue by joachimlindborg** [sameersbn/docker-openfire#9]
I run a fresh instance of the component and goes to the port 9090 to configure, final stage is to add the admin account. Which I now have tried to add in endless variants. When reloading to login, the server says *"Login failed" make sure you are an admin..*

I add my own domain for the server and all other configuration and a username password 
specialcase: Using domain names with "-" they are removed for default admin 

*Openfire 3.9.3 [Jun 12, 2015 1:58:54 AM]
Admin console listening at http://02fbe406ad71:9090
Missing database schema for openfire. Attempting to install...
Database update successful.*

after restart the domain name is right but I cannot login

and after changing the *<setup>true</setup>* to **false** in openfire.xml I get an error trying to change the admin password.

**Comment by joachimlindborg** [comment]
And the solution is to not add the full *domain.x* part when logging in just *admin* as user name sorry

**Comment by sameersbn** [comment]
@joachimlindborg glad that you got this resolved :+1:
